In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [4]:
a = np.array ({1,2,3})
print(a)
a

{1, 2, 3}


array({1, 2, 3}, dtype=object)

In [6]:
b = np.array ([[1,2,3],[4,5,6,],[7,8,9]])
print(b)
b

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
c = [[1,2,3],[4,5,6],[7,8,9]]
print(c)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


jumlah item dalam sebuah numpy array secara row axis harus seimbang/sama

setiap row punya item yang sama

## shorcut lain untuk numpy array selain np.array([])

In [12]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.empty(5)

array([9.83130635e-312, 3.99255407e+252, 4.38730294e-321, 1.90979625e-313,
       6.99442788e-009])

In [5]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [10]:
lima = np.arange(5,100,20)
lima

array([ 5, 25, 45, 65, 85])

## add, sort, remove

In [6]:
a = np.zeros(2)
b = np.ones(3)

np.append(a,b)

array([0., 0., 1., 1., 1.])

In [7]:
np.append(a, [1,2,3,4,5])

array([0., 0., 1., 2., 3., 4., 5.])

In [12]:
np.delete(lima,2)

array([ 5, 25, 65, 85])

In [13]:
acak = np.array([-12,4,8,-90,5,0,-9])
acak

array([-12,   4,   8, -90,   5,   0,  -9])

In [14]:
tersortir = np.sort(acak)
tersortir

array([-90, -12,  -9,   0,   4,   5,   8])

In [3]:
array3d = np.array([
    [[1,2,1,2],[3,4,5,6]],
    [[5,6,7,8],[8,5,6,2]],
    [[23,3,5,6],[5,99,6,7]]
])

In [5]:
np.ndim(array3d)

3

In [6]:
np.shape(array3d)
# kita akan dapat (3, 2, 4) yang artinya di level pertama ada 3 item
# setiap item tersebut (level2) isinya ada 2 element
# setiap element tersebut (level3) ada 4 barang lagi

(3, 2, 4)

In [7]:
np.size(array3d)

24

# reshape

In [10]:
hasil_reshape = array3d.reshape(4,6)
hasil_reshape

array([[ 1,  2,  1,  2,  3,  4],
       [ 5,  6,  5,  6,  7,  8],
       [ 8,  5,  6,  2, 23,  3],
       [ 5,  6,  5, 99,  6,  7]])

In [11]:
hasil_reshape = array3d.reshape(24,1)
hasil_reshape

array([[ 1],
       [ 2],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 8],
       [ 5],
       [ 6],
       [ 2],
       [23],
       [ 3],
       [ 5],
       [ 6],
       [ 5],
       [99],
       [ 6],
       [ 7]])

In [12]:
hasil_reshape = array3d.reshape(2,3,4)
hasil_reshape

array([[[ 1,  2,  1,  2],
        [ 3,  4,  5,  6],
        [ 5,  6,  7,  8]],

       [[ 8,  5,  6,  2],
        [23,  3,  5,  6],
        [ 5, 99,  6,  7]]])

# menambah dimensi array 

In [15]:
arr = np.arange(6)
arr

array([0, 1, 2, 3, 4, 5])

In [16]:
arr.ndim

1

In [21]:
arr2 = arr[np.newaxis, :] # merubah array 1 dimensi menjadi 2 dimensi. cara lain: np.expand_dims(arr, axis=0)
arr2

array([[0, 1, 2, 3, 4, 5]])

In [22]:
arr2.ndim

2

In [25]:
arr3 = arr[:, np.newaxis] # merubah array 1 dimensi menjadi 2 dimensi. cara lain: np.expand_dims(arr, axis=1)
arr3

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

apa perbedaan arr[np.newaxis, :] dengan arr[:, np.newaxis]?

bedany adalah axis mana yang ditambahkan menjadi dimensi baru.

untuk yang pertama, dia akan tambahin di axis 0 (row).

untuk yang kedua, dia akan tambahin di axis 1 (column).

In [33]:
# cara lain selain pakai np.newaxis adalah dengan pakai np.expand_dims
np.expand_dims(arr, axis=0)

array([[0, 1, 2, 3, 4, 5]])

In [32]:
np.expand_dims(arr, axis=1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

# indexing and slicing

indexing adalah mengambil 1 item di array/list menggunakan index nya

slicing adalah mengambil satu set item di array/list menggunakan index juga

In [34]:
arr

array([0, 1, 2, 3, 4, 5])

In [38]:
arr[0:3] # membuat array baru yang isinya ada 3 item, diambil dari arr index ke 0 sampai index ke 2

array([0, 1, 2])

In [36]:
arr[3]

3

In [37]:
arr[1:5]

array([1, 2, 3, 4])

In [39]:
arr[-2]

4

In [42]:
new = arr[1:5] # kalau hasilnya mau disimpan, masukkan ke variable
new

array([1, 2, 3, 4])

In [43]:
arr # arr tidak diubah oleh indexing ataupun slicing

array([0, 1, 2, 3, 4, 5])

In [44]:
acak = np.array([1,-99,-5,7,8,3,4,-12,0,-5])
acak

array([  1, -99,  -5,   7,   8,   3,   4, -12,   0,  -5])

In [47]:
acak[acak>0] # numpy array bisa terima kondisi sebagai index nya juga

array([1, 7, 8, 3, 4])

In [46]:
acak

array([  1, -99,  -5,   7,   8,   3,   4, -12,   0,  -5])

In [48]:
acak_genap = acak[acak % 2 == 0]
acak_genap

array([  8,   4, -12,   0])

In [50]:
acak_genap_lebih0 = acak[(acak % 2 == 0) & (acak>0)]
acak_genap_lebih0

array([8, 4])

# teknik lain untuk membuat numpy array 

vstack: vertical stack
hstack: horizontal stack
hsplit: horizontal split

In [51]:
arr1 = np.array([1,2,3,4,5,6,7])
arr2 = np.array([4,5,6,7,8,9,0])
arr_tumpuk12 = np.vstack((arr1,arr2))
# jadilah sebuah array 2 dimensi hasil "menumpuk" atau "stack"
# arr1 dan arr2:
arr_tumpuk12

array([[1, 2, 3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8, 9, 0]])

In [54]:
arr3 = np.array([[11,10],[1,2],[4,5]])
arr4 = np.array([[8,9],[1,4],[6,7]])
arr_tumpuk34 = np.vstack((arr3,arr4))
arr_tumpuk34

array([[11, 10],
       [ 1,  2],
       [ 4,  5],
       [ 8,  9],
       [ 1,  4],
       [ 6,  7]])

In [55]:
arr1 = np.array([1,2,3,4,5,6,7])
arr2 = np.array([8,9,10,11,12,13,14])
arr_tumpuk12 = np.hstack((arr1,arr2))
# horizontal stack menumpuk juga tapi dari kiri ke kanan
arr_tumpuk12

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [57]:
arr1 = np.array([[1,2], [3,4], [5,6]])
arr2 = np.array([[7,8], [9,10], [11,12]])
arr_tumpuk12 = np.hstack((arr1,arr2))
arr_tumpuk12

array([[ 1,  2,  7,  8],
       [ 3,  4,  9, 10],
       [ 5,  6, 11, 12]])

In [60]:
arr3 = np.array([[1,2,3,4,5],
               [6,7,8,9,10]])
arr3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [65]:
arr3.size

10

In [68]:
hasil_split = np.hsplit(arr3,5)
hasil_split

[array([[1],
        [6]]),
 array([[2],
        [7]]),
 array([[3],
        [8]]),
 array([[4],
        [9]]),
 array([[ 5],
        [10]])]

In [71]:
hasil_split[1]
# karena hasil split nya ada 3, diberikan dalam bentuk list
# kita bisa ambil menggunakan index

array([[2],
       [7]])

# numpy array bisa dihitung langsung

In [72]:
arr3 = np.array([[11,22,33,44,55],
                [66,77,88,99,89]])
arr3

array([[11, 22, 33, 44, 55],
       [66, 77, 88, 99, 89]])

In [74]:
arr3+1

array([[ 12,  23,  34,  45,  56],
       [ 67,  78,  89, 100,  90]])

In [75]:
arr3 - 10

array([[ 1, 12, 23, 34, 45],
       [56, 67, 78, 89, 79]])

In [76]:
arr3 * 8

array([[ 88, 176, 264, 352, 440],
       [528, 616, 704, 792, 712]])

In [77]:
arr3 % 2

array([[1, 0, 1, 0, 1],
       [0, 1, 0, 1, 1]], dtype=int32)

In [78]:
arr3.sum()

584

In [79]:
arr3

array([[11, 22, 33, 44, 55],
       [66, 77, 88, 99, 89]])

In [81]:
arr3.sum(axis=1)

array([165, 419])

# array operator lainnya 

maximum
minimum
sum (jumlah)
mean (rata-rata)

In [82]:
acak = np.array([1,2,3,4,5,6,7,8])
acak

array([1, 2, 3, 4, 5, 6, 7, 8])

In [84]:
acak.max()

8

In [85]:
acak.min()

1

In [86]:
acak.mean()

4.5

In [89]:
acak.sum()

36